# 全局模拟参数
global:
  dt: 1.0e-7
  steps: 10000
  seed: 123456
  step_average : 20
  step_write : 100

# 网格配置
grid:
  cells: [200, 200, 200]
  low_corner: [0.0, 0.0, 0.0]
  high_corner: [1, 1, 1]
  periodic: [false, false, false]
  halo_cell_width: 0

# 初始条件
initial:
  velocity: [1000.0, 0.0, 0.0]
  temperature: 273
  density: 9.282e-4
  Fn: 600000000000000

  max_collision_rate: 1.0e-20

# even though boundary type is static
boundary:
  - type: "periodic"
    axis: "x"
    slide: "min"
    temperature: 273
  - type: "periodic"
    axis: "x"
    slide: "max"
    temperature: 273
  - type: "periodic"
    axis: "y"
    slide: "min"
    temperature: 273
  - type: "periodic"
    axis: "y"
    slide: "max"
    temperature: 273
  - type: "periodic"
    axis: "z"
    slide: "min"
    temperature: 273
  - type: "periodic"
    axis: "z"
    slide: "max"
    temperature: 273

species:
  - name: "Argon"
    mass: 6.63e-26
    diam: 4.17e-10
    omega: 0.81
    Tref: 273
    Zrot: 0
    
  - name: "N2"
    mass: 4.6517e-26      # kg/molecule  (28.0134 g/mol / N_A)
    diam: 4.17e-10        # 有效碰撞直径，仍可用 4.17 Å（与 Ar 相同量级）
    omega: 0.74           # 粘度-温度指数（VHS/VSS 模型推荐 0.74）
    Tref: 273             # K
    Zrot: 5               # 298 K 附近的旋转松弛碰撞数（文献 4~6，取 5）

geo:
  filepath: "./run/sphere.stl"